### ISSUE TITLE
Disk Full /dev/loop0

### ISSUE THREAD

**Issue by christianblunden** [TheNewNormal/coreos-osx#20]
After a few days usage I will get a repeatable Disk Full error

`df -h` shows `/dev/loop0` mounted at `/usr` is at 100%, the size allocated is only 196M

Resolution at the moment is to destroy VM and recreate. Is there a better way or is this amount editable?

**Comment by christianblunden** [comment]
```
Error pulling image (latest) from docker.io/XXXX, ApplyLayer exit status 1 stdout:  stderr: open /usr/lib/python3.4/lib2to3/fixes/fix_paren.py: no space left on device/fixes/fix_paren.py: no space left on device
ERROR: Error pulling image (latest) from docker.io/XXXX, ApplyLayer exit status 1 stdout:  stderr: open /usr/lib/python3.4/lib2to3/fixes/fix_paren.py: no space left on device
```

```
core@core-01 ~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        891M     0  891M   0% /dev
tmpfs          1003M     0 1003M   0% /dev/shm
tmpfs          1003M   17M  987M   2% /run
tmpfs          1003M     0 1003M   0% /sys/fs/cgroup
/dev/vda        4.8G  563M  4.0G  13% /
/dev/loop0      196M  196M     0 100% /usr
tmpfs          1003M     0 1003M   0% /tmp
tmpfs          1003M     0 1003M   0% /media
```

**Comment by rimusz** [comment]
that's weird, I have encountered that problem before. which CoreOS channel you are using?
btw I have a new version which is not using root drive anymore but map one drive to different folders for docker, rkt, etcd persistence. will release it next week

**Comment by christianblunden** [comment]
using the alpha channel. I just updated to v1.1.4 (from v1.1.1), so will see if this has any effect

**Comment by rimusz** [comment]
btw `/dev/loop0` is by default read-only partition on CoreOS, so it cannot cause any problems for you.

Maybe persistent `/dev/vda` disk size is too small for you, just create it as a bigger one.
