### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by christianblunden** [TheNewNormal/coreos-osx#28]
VM runs out of disk space despite OS reporting Gigabytes of space 

`ERROR: Error pulling image (latest) from docker.io/wurstmeister/zookeeper, ApplyLayer exit status 1 stdout:  stderr: open /usr/sbin/zic: no space left on device`

SSH into VM

```bash
df -h

devtmpfs        891M     0  891M   0% /dev
tmpfs          1003M     0 1003M   0% /dev/shm
tmpfs          1003M   17M  987M   2% /run
tmpfs          1003M     0 1003M   0% /sys/fs/cgroup
/dev/vda        4.8G  2.3G  2.4G  49% /
/dev/loop0      196M  196M     0 100% /usr
tmpfs          1003M     0 1003M   0% /tmp
tmpfs          1003M     0 1003M   0% /media
```

`/dev/vda` only 49% full with 2.4G available

**Comment by rimusz** [comment]
it is not a bug, it is how docker images use disk space. check that with `df -i`
