### ISSUE TITLE
wrong network address

### ISSUE THREAD

**Issue by cobrowserAlex** [TheNewNormal/coreos-osx#33]
I seem to get a wrong network address, after updating to 1.2.1 from 1.1.8. I upgraded because I was not able to reach my docker registry anymore. Is there a way to get the 64 address back?
```
$ /Applications/CoreOS.app/Contents/Resources/up.command; exit;

Starting Docker Registry v2 on 192.168.64.1:5000 ...

Starting VM ...

> booting core-01
[corectl] beta/899.6.0 already available on your system
[corectl] '/Users/alex' was made available to VMs via NFS
[corectl] started 'core-01' in background with IP 192.168.65.2 and PID 1331

Waiting for VM to be ready...
-
etcdctl ls /:

fleetctl list-machines:
/Applications/CoreOS.app/Contents/Resources/up.command: line 131: fleetctl: command not found

fleetctl list-units:
/Applications/CoreOS.app/Contents/Resources/up.command: line 146: fleetctl: command not found

bash-3.2$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
bash-3.2$ curl 192.168.64.1:5000/v2/
curl: (7) Failed to connect to 192.168.64.1 port 5000: Network is unreachable
```

**Comment by rimusz** [comment]
I have not updated kube Apps to the latest corectl which has that network fix, only did the coreos vm app. was planning to release new kube apps versions next week

**Comment by rimusz** [comment]
@cobrowserAlex the latest version of this App has already the network fix, please try it out.

**Comment by cobrowserAlex** [comment]
wow, that's fast @rimusz I'll give it a try!

**Comment by cobrowserAlex** [comment]
I just tried the latest kube-solo-osx, since that had a new release already and got this output:
```
$ /Applications/Kube-Solo.app/Contents/Resources/up.command; exit;

Starting VM ...
> booting k8solo-01
[corectl] stable/835.12.0 already available on your system
[corectl] '/Users/alexknol' was already available to VMs via NFS
[corectl] started 'k8solo-01' in background with IP 192.168.65.3 and PID 8470

Waiting for VM to be ready...
-
fleetctl list-machines:
MACHINE		IP		METADATA
118af633...	192.168.65.3	-

Waiting for Kubernetes cluster to be ready. This can take a few minutes...
\error: couldn't read version from server: Get http://192.168.64.3:8080/api: dial tcp 192.168.64.3:8080: network is unreachable
|error: couldn't read version from server: Get http://192.168.64.3:8080/api: dial tcp 192.168.64.3:8080: network is unreachable
/error: couldn't read version from server: Get http://192.168.64.3:8080/api: dial tcp 192.168.64.3:8080: network is unreachable
-error: couldn't read version from server: Get http://192.168.64.3:8080/api: dial tcp 192.168.64.3:8080: network is unreachable
```

**Comment by rimusz** [comment]
from your output it does not look that Kubernetes fleet units are installed there

**Comment by rimusz** [comment]
in the next version I'm going to add the check for Kubernetes fleet units running state

**Comment by rimusz** [comment]
also I see your VM still has IP from 65 range

**Comment by cobrowserAlex** [comment]
I believe the 65 range is the problem. I haven't told it to do that, it just happened. Do you know how I can set it back to use 64 range?

**Comment by rimusz** [comment]
@AntonioMeireles so it looks like the network fix does not work properly yet

**Comment by AntonioMeireles** [comment]
@rimusz this is odd. my guess is that for some reason local images aren't being rebuilt (in order for them to consume the fix). _researching_.

**Comment by cobrowserAlex** [comment]
I did have a docker-machine that i briefly had on 192.169.64.*, but since changed back to 192.168.99.* network and thereafter removed. Dunno if that is of any influence..

**Comment by AntonioMeireles** [comment]
_may_ had, @cobrowserAlex can you check please if things work with it now elsewhere ?

**Comment by cobrowserAlex** [comment]
I see that in VirtualBox there was still a hostOnly network defined with ip 192.168.64.1. Probably because I tried the docker-machine on that address. Removed that and now rebuilding the coreos-osx vm..

**Comment by cobrowserAlex** [comment]
No avail. Still coming up with 65 address, before and after mac reboot.

**Comment by AntonioMeireles** [comment]
@cobrowserAlex paste please here full `corectl version`  output

**Comment by AntonioMeireles** [comment]
@cobrowserAlex 

on your setup running `defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist Shared_Net_Address` gives you what ?

**Comment by cobrowserAlex** [comment]
alexknol@Alexs-MacBook-Pro~/coreos-osx $ bin/corectl version
CoreOS over OSX made simple.
 - http://github.com/TheNewNormal/corectl
   Copyright (c) 2015-2016, António Meireles

Running version: 0.5.4
                 built with go1.5.3, 2016-01-28 10:09:22 +0000 WET
Latest upstream: 0.5.4

$ defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist Shared_Net_Address
192.168.65.1

**Comment by cobrowserAlex** [comment]
Removing this file and rebuilding the vm works.
```
mv /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist.backup
```

**Comment by cobrowserAlex** [comment]
So now things are back the the old issue: when I halt the vm and then put my mac to sleep, the next morning, the vm boots normal, docker seems to work, but the registry is unreachable.

Only after I reboot the Mac and start the VM, the registry is reachable.

**Comment by rimusz** [comment]
strange I do use the coreos-osx VM the same way as you do and never had problems with the registry after mac's sleep. 
You mentioned you have some work vpn, maybe that is causing the problem for you?

**Comment by cobrowserAlex** [comment]
I will dig a bit more into what the exact steps to reproduce are.

**Comment by cobrowserAlex** [comment]
wow, I halted the VM yesterday and brought it back up today. Now the Registry is not reachable again.
What am I doing wrong here?
```
Enter passphrase for /Users/alexknol/.ssh/id_rsa:

etcdctl ls /:

fleetctl list-machines:
MACHINE		IP		METADATA
39e5365b...	192.168.64.7	-

fleetctl list-units:
UNIT			MACHINE				ACTIVE	SUB
dockerui.service	39e5365b.../192.168.64.7	active	running
fleet-ui.service	39e5365b.../192.168.64.7	active	running

bash-3.2$ curl http://192.168.64.1:5000/v2/
curl: (7) Failed to connect to 192.168.64.1 port 5000: Connection refused
bash-3.2$
```

**Comment by rimusz** [comment]
@cobrowserAlex can you do `ps aux | grep "[r]egistry config.ml" ` for me please?

**Comment by rimusz** [comment]
I noticed that happens time by time too, it looks it is the problem with the latest registry version. 
I do build the go code from master source to be run as a Mac app. 
Will introduce extra check to be sure registry gets started

**Comment by cobrowserAlex** [comment]
wow, thanks @rimusz. When i saw this this morning I rebooted my mac and was still unable to reach the registry. Before you commented I rebooted again and now it works again. Definately something flakey here.
```
Starting Docker Registry v2 on 192.168.64.1:5000 ...

Starting VM ...

> booting core-01
[corectl] stable/835.12.0 already available on your system
[corectl] '/Users/alexknol' was already available to VMs via NFS
[corectl] started 'core-01' in background with IP 192.168.64.7 and PID 788

Waiting for VM to be ready...
-
etcdctl ls /:

fleetctl list-machines:
MACHINE		IP		METADATA
fbc0dfe8...	192.168.64.7	-

fleetctl list-units:
UNIT	MACHINE	ACTIVE	SUB

bash-3.2$ ps aux | grep "[r]egistry config.yml"
alexknol          774   0.0  0.1 573422276   9316 s000  S    10:54AM   0:00.04 registry config.yml
bash-3.2$ curl http://192.168.64.1:5000/v2/
{}bash-3.2$
```

**Comment by cobrowserAlex** [comment]
p.s. really appreciating the good work you guys do here!

**Comment by rimusz** [comment]
@AntonioMeireles does the awesome job with `corectl`, I use it for my Apps then :)

**Comment by rimusz** [comment]
@cobrowserAlex 

registry problem is fixed with the v1.2.2 release

we dot have the Slack team for that yet, as we are just two guys busy with our day $jobs too

**Comment by cobrowserAlex** [comment]
Great, I will test soon!

**Comment by rimusz** [comment]
I think we can close this issue as it covers two different problems
