### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by mmikulicic** [TheNewNormal/coreos-osx#35]
Hi,

I downloaded https://github.com/TheNewNormal/coreos-osx/releases/download/v1.2.1/CoreOS_v1.2.1.dmg
followed the instructions on the terminal, selected `alpha` and got an error message that instructed me to open ~/coreos-osx/logs/first-init_vm_up.log and report an issue.

Here's the content of the log file:

```
> booting core-01
Error: open alpha: no such file or directory

Usage:
  corectl load path/to/yourProfile [flags]

Examples:
  corectl load profiles/demo.toml

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"
```

**Comment by rimusz** [comment]
did you run it from the dmg or copied to desktop/applications?

**Comment by mmikulicic** [comment]
copied to /Applications

**Comment by rimusz** [comment]
what is in your `~/coreos-osx/` folder?

**Comment by mmikulicic** [comment]
```
/Users/mkm/coreos-osx:
bin  cloud-init  data.img  docker_images  fleet  logs  my_fleet  registry  settings  tmp

/Users/mkm/coreos-osx/bin:
corectl  docker-exec  docker2aci  etcdctl  gsed  jq  pv  registry  rkt  wget

/Users/mkm/coreos-osx/cloud-init:
user-data

/Users/mkm/coreos-osx/docker_images:

/Users/mkm/coreos-osx/fleet:
dockerui.service  fleet-ui.service

/Users/mkm/coreos-osx/logs:
first-init_vm_up.log  vm_up.log

/Users/mkm/coreos-osx/my_fleet:

/Users/mkm/coreos-osx/registry:
config.yml

/Users/mkm/coreos-osx/settings:
core-01.toml

/Users/mkm/coreos-osx/tmp:
```

**Comment by rimusz** [comment]
can you show the `/Users/mkm/coreos-osx/settings/core-01.toml` content, please?

**Comment by mmikulicic** [comment]
```
[core-01]
   uuid = "D1024138-F21A-4C61-8F40-ADCFC358D942"
   channel = "alpha"
   volume = "data.img"
   cloud_config = "cloud-init/user-data"
   cpus = 2
   memory = "2048"
   local = "true"
   sshkey = 'ssh-rsa AAAAB3....<rest of pubkey redacted>'
```

**Comment by rimusz** [comment]
hmm, that looks fine, can you try to boot up vm via menu "Up"?

**Comment by mmikulicic** [comment]
I tried and it hanged while waiting at the VM to boot. Didn't capture the logs now I'm AFK

**Comment by rimusz** [comment]
right, very weird, never had such issue before.
ok, on more check
Can you try different channel, e.g. beta or stable? 
You can change that via menu Setup -> Change Release Channel

Also before doing that are any folders/files in `/.coreos/images/alpha` folder ?

Just trying to think about all possible problems

**Comment by mmikulicic** [comment]
```
$ ls -R ~/.coreos/images/alpha
/Users/mkm/.coreos/images/alpha:
949.0.0

/Users/mkm/.coreos/images/alpha/949.0.0:
coreos_production_pxe.vmlinuz  coreos_production_pxe_image.cpio.gz
```

I'll try another channel

**Comment by rimusz** [comment]
all files are in place, very strange issue.

which OS X version are you using?

**Comment by mmikulicic** [comment]
10.10.5

I have virtualbox running

**Comment by rimusz** [comment]
Ah, I see.
I use the latest 10.11.3
Have you tried to reboot your Mac and usually having virtualbox on, makes things worse

**Comment by rimusz** [comment]
as this issue related to the alpha channel OS, we have the separate issue opened for it https://github.com/TheNewNormal/corectl/issues/62 I'm going to close this one then
