### ISSUE TITLE
Data does not survive VM reboots

### ISSUE THREAD

**Issue by joelchen** [TheNewNormal/coreos-osx#40]
Copied systemd service file to /home/core with SCP, then copied the service file from /home/core to /etc/systemd/system. Started the systemd service, exited SSH, quit CoreOS for OS X v1.2.1, and launched CoreOS for OS X v1.2.1 again.

Started VM with Up menu option, followed by SSH to VM. The systemd service file is missing at both /home/core and /etc/systemd/system. However, running `docker images` showed that Docker images survived.

**Comment by rimusz** [comment]
@joelchen the VM has no `root` disk as CoreOS runs from RAM from [ISO](https://coreos.com/os/docs/latest/booting-with-iso.html)  and only these folders are mounted to persist data:
```
/data/var/lib/docker -> /var/lib/docker
/data/var/lib/rkt -> /var/lib/rkt
/data/var/lib/etcd2 -> /var/lib/etcd2
/data/opt/bin -> /opt/bin
```
Just add your systemd services to `cloud-init` or make a fleet unit

**Comment by joelchen** [comment]
@rimusz Thanks for the quick reply. Any plans to make data to persist? I would like to include a custom .bashrc in /home/core for instance.

Do I need to configure things to make Fleet-UI and DockerUI on the menu work? They point to http://192.168.64.2:3000 and http://192.168.64.2:9000 respectively with "Safari Can't Connect to the Server". The commands `fleetctl list-units` and `fleetctl list-unit-files` return nothing even after I copied the service file into ~/coreos-osx/fleet directory and reboot the VM.

**Comment by rimusz** [comment]
@joelchen we had too many issues using `root` disk, so that was scrapped off.

fleet-ui and docker-ui should work when their docker images get downloaded, check fleet units status why they are not running.

to have your fleet units installed automatically as per readme:
```
Put your fleet units into ~/coreos-osx/my_fleet folder and they will be automaticly started on each VM boot
```

**Comment by joelchen** [comment]
@rimusz I see. Would appreciate other creative ways for persistent data (e.g. rsync), since there are many issues using `root` disk.

**Comment by rimusz** [comment]
@joelchen you can take an advantage of NFS mounted disk:
```
Mac user home folder is automaticly mounted to VM: /Users/my_user:/Users/my_user
```

**Comment by joelchen** [comment]
@rimusz Great, thank you.

**Comment by rimusz** [comment]
as this one is not the bug I'm going to close it
