### ISSUE TITLE
Possibility to use a different directory

### ISSUE THREAD

**Issue by julienmarie** [TheNewNormal/coreos-osx#42]
Hi,
I'm trying to use coreos-osx by putting the folder on an external drive ( symlinking it ), but it can't launch ( core01 not found or dead ).
Is there a way to use another directory ? 

Thanks

**Comment by rimusz** [comment]
@julienmarie I have not tested to symlink the whole folder, but guys have success to symlink the `data.img` file to another location

**Comment by rimusz** [comment]
closing in favour of #30
