### ISSUE TITLE
Docker build crash : A lot of no such file or directory

### ISSUE THREAD

**Issue by kvacquier** [TheNewNormal/coreos-osx#66]
When I try to do a Docker build i have a lot of missing directories, during step one (need to do 
bash-4.2# mkdir /var/lib/docker/image/overlay/imagedb/
bash-4.2# mkdir /var/lib/docker/image/overlay/imagedb/content/
bash-4.2# mkdir /var/lib/docker/image/overlay/imagedb/content/sha256/
)
But then, during step 2 i have the following error : internal failure while setting the bit: open /var/lib/docker/network/files/local-kv.db: no such file or directory

**Comment by rimusz** [comment]
@kvacquier which coreos channel you are using:
alpha
beta
stable

**Comment by kvacquier** [comment]
I've tried with both alpha and stable

Le ven. 3 juin 2016 à 13:06, Rimas Mocevicius <notifications@github.com> a
écrit :

**Comment by rimusz** [comment]
@kvacquier would you mind to try the latest v1.3.0, please.
But first delete the `~/coreos-osx/data.img` file before running the new version of the App

**Comment by rimusz** [comment]
@kvacquier closing this one as I'm not able to reproduce your problem, plus I have released new v1.4.1 for the App, please try it.
