### ISSUE TITLE
Error when I try running up

### ISSUE THREAD

**Issue by bencooling** [TheNewNormal/coreos-osx#73]
I am using:
- OS X 10.11.5
- CoreOS for OS X v1.3.0

When I try `Up` from the Core OS status bar menu I get the following in the shell:

```zsh
Applications/CoreOS.app/Contents/Resources/up.command; exit;

Starting Docker Registry v2 on 192.168.64.1:5000 ...

Starting VM ...

> booting core-01
[corectl] stable/1010.5.0 already available on your system
Error: unable to validate /etc/exports ('[]')
```

**Comment by AntonioMeireles** [comment]
@bencooling - thanks for reporting; what do you have in you `/etc/exports` ? (paste here plz)

**Comment by bencooling** [comment]
@AntonioMeireles didn't even think of that! The contents of `/etc/exports` is:

```
# BEGIN: dlite
/Users -network 192.168.64.0 -mask 255.255.255.0 -alldirs -maproot=root:wheel
# END: dlite
```

So I guess I can't have [dlite](https://github.com/nlf/dlite) running also?

**Comment by AntonioMeireles** [comment]
well... point is one can't export a subdir of a dir that is already being exported. in the past we were exporting `/Users` but then people complained as some wanted to be able to run several corectl sessions in parallel as != users so we went to exporting the ${homedir} which conflicts with dlite's scheme. 

for next major version we're thinkering on getting this more flexible, resilient but for now and before you call `corectl`, yes, you can't have `dlite` running...

**Comment by bencooling** [comment]
Thanks for the explanation!

**Comment by rimusz** [comment]
@bencooling v1.4.1 has the option NFS to turn it on, by default is disabled
