### ISSUE TITLE
No option to turn NFS off

### ISSUE THREAD

**Issue by joshdekock** [TheNewNormal/coreos-osx#76]
There wasn't anything in the README about NFS, how can I turn this feature off if I do not want it?

**Comment by AntonioMeireles** [comment]
ATM you don't. it's on our roadmap. _soon_ you will (probably mid to late next week).

**Comment by rimusz** [comment]
@joshdekock v1.4.1 has the option NFS to turn it on/off

**Comment by chloe** [comment]
Awesome, thanks!
