### ISSUE TITLE
hyperkit and windows

### ISSUE THREAD

**Issue by joeblew99** [TheNewNormal/coreos-osx#84]
Some of the guys are on windows, so i started to look to see if i can run CoreOS for them on their Windows Machine.

Docker for Windows i assume has the same capabilities as Docker for Mac, but when i look at the Hyperkit github repo it does not seem to have any Windows support.

Can anyone fill me in about what is going on here ? Is the Windows support maybe closed source and not on the docker github repo at at all ?

**Comment by rimusz** [comment]
not sure that this ones related to coreos-ox App, you should better ask at Hyperkit repo
