### ISSUE TITLE
Please add command line to start and stop CoreOS

### ISSUE THREAD

**Issue by TheIndifferent** [TheNewNormal/coreos-osx#85]
The tool is amazing, gives way more confidence than Alpine-based official docker for mac. But lacks some command line control possibilities. Please add (or document if already exists) the functionality similar to `docker-machine`, to make it possible to start, stop and show info of the running CoreOS from bash scripts. Example use-case is maven build which uses docker images for integration tests:
```
# cat ~/.mavenrc
#!/bin/bash

## on mac the path is empty when maven is launched from other application,
## adding most important stuff to the path:
export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
echo "PATH is set to: $PATH"

## checking if docker-vm is in running state, launching if needed:
if [[ "$( docker-machine status docker-vm )" != 'Running' ]]
then
    echo 'docker-vm is not running, starting...'
    docker-machine start docker-vm
    echo 'docker-vm started.'
else
    echo 'docker-vm is running.'
fi

## printing out docker-machine env:
echo 'setting docker-vm env variables...'
eval $( docker-machine env docker-vm )
echo 'docker-vm variables are set:'
echo "DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY"
echo "DOCKER_HOST=$DOCKER_HOST"
echo "DOCKER_CERT_PATH=$DOCKER_CERT_PATH"
echo "DOCKER_MACHINE_NAME=$DOCKER_MACHINE_NAME"
echo ''
```

**Comment by AntonioMeireles** [comment]
hi @TheIndifferent,

thanks for your kind words!

please take a look at  [corectl](https://github.com/TheNewNormal/corectl) (from which [cores-osx](github.com/TheNewNormal/coreos-osx) is *just* a wrapper) as it should do everything you asked for and more 😄. And if not just open a new feature request...  

Have a great weekend!

**Comment by TheIndifferent** [comment]
I see, very nice, thanx for the info! Is it possible to pass `core-01.toml` file as an argument to `corectl`?

**Comment by rimusz** [comment]
@TheIndifferent yes, check it here https://github.com/TheNewNormal/coreos-osx/blob/master/src/up.command#L73

I have plans to have similar functionality via cli as in docker for mac.
or if you have any suggestions or PRs which would we very welcome too :-)

**Comment by TheIndifferent** [comment]
Awesome, thank you very much. I am closing the issue then.

**Comment by rimusz** [comment]
@TheIndifferent  here we go you can control VM via cli: https://github.com/TheNewNormal/coreos-osx/releases/tag/v1.4.8
