### ISSUE TITLE
Minimum OS X Requirement

### ISSUE THREAD

**Issue by whitlockjc** [TheNewNormal/coreos-osx#89]
I just realized that homebrew had some old versions of this project and kube-solo.  Upon updating to the latest coreos-osx I'm told I cannot run it because it requires OS X 10.11.x.  Is this on purpose?

**Comment by whitlockjc** [comment]
corectl.app has the same issue.  If there is a reason to require 10.11.x that's cool but if not, it would be great if these could be rebuilt allowing 10.10.x at least.

**Comment by rimusz** [comment]
@whitlockjc can you check that corectl (Not the corectl.app) works for you, as it is built for 10.11 by @AntonioMeireles , if it does work i can change all apps to support 10.10 again

**Comment by whitlockjc** [comment]
Here is the output:

```
/Applications/corectl.app/Contents/Resources/bin/corectl version
 Version:       0.7.12
 Go Version:    go1.6.3
 Built:         Tue Jul 19 11:05:24 WEST 2016
 OS/Arch:       darwin/amd64
--
 suggested version is 0.7.13
```

It seems that `corectl` in `/Applications/corectl.app/Contents/Resources/bin` works just fine, although the one in `/Applications/corectl.app/Contents/MacOS` fails, which I think is expected.

**Comment by rimusz** [comment]
check this one directly https://github.com/TheNewNormal/corectl/releases/tag/v0.7.13

**Comment by whitlockjc** [comment]
Runs fine:

```
./corectl version
 Version:       0.7.13
 Go Version:    go1.6.3
 Built:         Thu Jul 21 16:33:58 WEST 2016
 OS/Arch:       darwin/amd6
```

**Comment by rimusz** [comment]
ok i will rebuild all apps to support 10.10 over weekend

**Comment by rimusz** [comment]
any reason you are not on 10.11?

**Comment by whitlockjc** [comment]
I didn't want to spend the time.  :)  _(I'm not a big fan of upgrading and usually end up doing a backup, clean install, restore which isn't fast.)_  I'd hate to upgrade just for this.  Also, I wonder if this is why homebrew hasn't been updated?  Supporting at least one version back is pretty common.

**Comment by rimusz** [comment]
no idea who does homebrew for my apps, i know @AntonioMeireles does it for corectl.
all four apps include updates check, so no homebrew is needed :)
i do not have problems upgrading between macOS versions, have not done the clean update for ages

**Comment by rimusz** [comment]
also corectl.app handles corectl tools upgrade in place

**Comment by whitlockjc** [comment]
I don't mind upgrading but I hope I don't have to for this.  :)

**Comment by rimusz** [comment]
@whitlockjc v1.4.6 supports macOS 10.10 too

**Comment by whitlockjc** [comment]
Thanks a lot @rimusz.
